import{S as y,i as h,a as L}from"./assets/vendor-da186403.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const i={container:document.querySelector(".container"),form:document.querySelector(".form"),btn:document.querySelector(".form-button"),loader:document.querySelector(".loader"),galleryList:document.querySelector(".gallery"),loadMore:document.querySelector(".btn-load-more"),input:document.querySelector("input")};function u(){i.loader.classList.remove("hidden")}function m(){i.loader.classList.add("hidden")}function v(e){const{largeImageURL:r,webformatURL:s,tags:n,likes:t,downloads:o,views:a,comments:g}=e;return`<li class="gallery-item">
        <a href="${r}" class="gallery-link">
          <img
            src="${s}"
            class="gallery-image"
            alt="${n}"
          />
        </a>
        <div class="description">
            <div class="description-item"><p>Likes</p><span>${t}</span></div>
            <div class="description-item"><p>Downloads</p><span>${o}</span></div>
            <div class="description-item"><p>Views</p><span>${a}</span></div>
            <div class="description-item"><p>Comments</p><span>${g}</span></div>
        </div>
      </li>`}function f(e){const r=e.data.map(v).join("");totalHits>perPage&&i.loadMore.classList.remove("hidden"),e.data.length&&(i.galleryList.insertAdjacentHTML("beforeend",r),new y(".gallery a",{captions:!0,captionSelector:"img",captionPosition:"bottom"}).refresh())}const p="Sorry, there are no images matching your search query. Please try again!",b="We are sorry, but you have reached the end of search results.";function c(e){h.error({position:"topRight",maxWidth:"432",backgroundColor:"#ef4040",messageColor:"#fafafb",messageSize:"16px",message:e})}function S(){if(page>1){const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2,left:0,behavior:"smooth"})}}i.form.addEventListener("submit",w);i.loadMore.addEventListener("click",M);let q="",d=1;async function l(e){const r="https://pixabay.com",s="/api/",n="?key=42447990-17cd7de231c9689be9e26f0f6",t=`&q=${e}&image_type=photo&orientation=horizontal&safesearch=true`,o=r+s+n+t;return(await L.get(o)).data}l("potatos");async function w(e){e.preventDefault(),d+=1,i.galleryList.innerHTML="";const r=e.target.elements.query.value.trim();if(!r){i.form.elements.input.value="",c(console.error());return}u();try{const s=await l(r);f(s),P(s,d),console.log(s)}catch{c(p)}finally{m()}i.form.reset(),i.loadMore.classList.remove("hidden")}async function M(){u();try{const e=await l(q);f(e),S(),m()}catch{c(p)}}function P(e,r){const s=Math.ceil(e.totalHits/15);console.log(s),s<=r?(i.loadMore.classList.add("hidden"),i.loader.classList.add("hidden"),iziToast.error(b)):i.loadMore.classList.remove("hidden")}
//# sourceMappingURL=commonHelpers.js.map
